apiVersion: apps/v1
kind: Deployment
metadata:
  name: valeo-neuroerp-operator
  namespace: valeo-system
  labels:
    app: valeo-neuroerp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valeo-neuroerp-operator
  template:
    metadata:
      labels:
        app: valeo-neuroerp-operator
    spec:
      serviceAccountName: valeo-neuroerp-operator
      containers:
      - name: operator
        image: valeo-neuroerp/operator:v1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "valeo-neuroerp-operator"
        ports:
        - containerPort: 8080
          name: metrics
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: valeo-neuroerp-operator
  namespace: valeo-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: valeo-neuroerp-operator
  namespace: valeo-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - valeo-neuroerp-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - valeo.neuroerp.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: valeo-neuroerp-operator
  namespace: valeo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: valeo-neuroerp-operator
subjects:
- kind: ServiceAccount
  name: valeo-neuroerp-operator
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: valeoapps.valeo.neuroerp.com
spec:
  group: valeo.neuroerp.com
  names:
    kind: ValeoApp
    listKind: ValeoAppList
    plural: valeoapps
    singular: valeoapp
    shortNames:
    - vapp
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
                minimum: 1
                description: Anzahl der Replikate für die Anwendung
              image:
                type: string
                description: Docker-Image für die Anwendung
              version:
                type: string
                description: Version der Anwendung
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
              modules:
                type: array
                items:
                  type: string
                description: Liste der aktivierten Module
              database:
                type: object
                properties:
                  type:
                    type: string
                    enum: [postgres, mysql, mongodb]
                  version:
                    type: string
                  size:
                    type: string
            required:
            - size
            - image
            - version
          status:
            type: object
            properties:
              phase:
                type: string
              message:
                type: string
              readyReplicas:
                type: integer
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Version
      type: string
      jsonPath: .spec.version
    - name: Replicas
      type: integer
      jsonPath: .spec.size
    - name: Ready
      type: integer
      jsonPath: .status.readyReplicas
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
---
apiVersion: v1
kind: Service
metadata:
  name: valeo-neuroerp-operator-metrics
  namespace: valeo-system
  labels:
    app: valeo-neuroerp-operator
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app: valeo-neuroerp-operator 