# Alertmanager-Konfiguration für das ERP-System
# Diese Datei definiert die Routing-Regeln und Empfänger für Warnungen

global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/XXXXXXXXXX'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'pagerduty'
    continue: true
  - match:
      severity: critical
    receiver: 'sms-alerts'
    continue: true
  - match_re:
      severity: ^(critical|high)$
    receiver: 'email-alerts'
    continue: true
  - match:
      severity: high
    receiver: 'slack-notifications'
    continue: true
  - match:
      severity: medium
    receiver: 'slack-notifications'
    group_wait: 1m
    group_interval: 10m
    repeat_interval: 8h
  - match:
      severity: low
    receiver: 'slack-low-priority'
    group_wait: 5m
    group_interval: 30m
    repeat_interval: 24h

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'high'
    equal: ['alertname', 'job']
  - source_match:
      severity: 'high'
    target_match:
      severity: 'medium'
    equal: ['alertname', 'job']
  - source_match:
      severity: 'medium'
    target_match:
      severity: 'low'
    equal: ['alertname', 'job']

receivers:
- name: 'pagerduty'
  pagerduty_configs:
  - service_key: '<pagerduty-service-key>'
    send_resolved: true
    description: '{{ .GroupLabels.alertname }}'
    details:
      summary: '{{ .Annotations.summary }}'
      description: '{{ .Annotations.description }}'
      severity: '{{ .Labels.severity }}'
      component: '{{ .Labels.job }}'
      runbook: '{{ .Annotations.runbook_url }}'

- name: 'email-alerts'
  email_configs:
  - to: 'erp-alerts@example.com'
    send_resolved: true
    html: |
      <!DOCTYPE html>
      <html>
      <body>
        <h1>{{ .Status | toUpper }}</h1>
        <h2>{{ .GroupLabels.alertname }}</h2>
        <p><strong>Zusammenfassung:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Beschreibung:</strong> {{ .Annotations.description }}</p>
        <p><strong>Schweregrad:</strong> {{ .Labels.severity }}</p>
        <p><strong>Komponente:</strong> {{ .Labels.job }}</p>
        <p><a href="{{ .Annotations.runbook_url }}">Runbook</a></p>
      </body>
      </html>

- name: 'slack-notifications'
  slack_configs:
  - channel: '#erp-alerts'
    send_resolved: true
    title: '{{ .Status | toUpper }}: {{ .GroupLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Details:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Runbook:* {{ .Annotations.runbook_url }}
      {{ end }}
    actions:
    - type: button
      text: 'Runbook'
      url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
    - type: button
      text: 'Grafana'
      url: 'https://grafana.example.com/d/xyz/erp-system-overview'

- name: 'slack-low-priority'
  slack_configs:
  - channel: '#erp-monitoring'
    send_resolved: false
    title: '{{ .Status | toUpper }}: {{ .GroupLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Details:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
      {{ end }}

- name: 'sms-alerts'
  webhook_configs:
  - url: 'https://sms-gateway.example.com/send'
    send_resolved: false
    http_config:
      basic_auth:
        username: 'sms-user'
        password: 'sms-password'
    max_alerts: 5 