version: '3.8'

services:
  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: valeo-neuroerp-backend
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Berlin
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: valeo-neuroerp-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=valeo_neuroerp
      - POSTGRES_USER=valeo_user
      - POSTGRES_PASSWORD=valeo_password
      - TZ=Europe/Berlin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: valeo-neuroerp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local 