# Automatisch generierte Docker Compose-Datei

version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: valeo_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - valeo_network

  # Multi-Agent System Service
  mas:
    build:
      context: .
      dockerfile: docker/mas.Dockerfile
    container_name: valeo_mas
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017
      - MONGODB_DB=${MONGODB_DB}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./backups:/app/backups
    networks:
      - valeo_network

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: valeo_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - valeo_network

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: valeo_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - valeo_network

  # Alert Manager Service
  alertmanager:
    image: prom/alertmanager:latest
    container_name: valeo_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - valeo_network

  # Node Exporter Service
  node-exporter:
    image: prom/node-exporter:latest
    container_name: valeo_node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - valeo_network

  # Backup Service
  backup:
    build:
      context: .
      dockerfile: docker/backup.Dockerfile
    container_name: valeo_backup
    depends_on:
      - mongodb
    volumes:
      - ./backups:/backups
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017
      - MONGODB_DB=${MONGODB_DB}
      - BACKUP_DIR=/backups
      - BACKUP_RETENTION_DAYS=7
    networks:
      - valeo_network

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  valeo_network:
    driver: bridge
