# Automatisch generierte Docker Compose-Datei

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: infrastructure/docker/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=valeo_neuroerp
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=valeo_neuroerp
      - POSTGRES_USER=valeo
      - POSTGRES_PASSWORD=secure_password
      - REDIS_HOST=redis
    depends_on:
      - mongodb
      - postgres
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  worker:
    build:
      context: .
      dockerfile: infrastructure/docker/worker/Dockerfile
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=valeo_neuroerp
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=valeo_neuroerp
      - POSTGRES_USER=valeo
      - POSTGRES_PASSWORD=secure_password
      - REDIS_HOST=redis
    depends_on:
      - mongodb
      - postgres
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=valeo_neuroerp
      - POSTGRES_USER=valeo
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./infrastructure/docker/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
