version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:v1.8.4
    container_name: valero_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334

  chroma:
    image: chromadb/chroma:latest
    container_name: valero_chroma
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/chroma/storage