apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-manager
  namespace: valeo-neuroerp
  labels:
    app: cache-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache-manager
  template:
    metadata:
      labels:
        app: cache-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: cache-manager
        image: valeo-neuroerp/cache-manager:1.1
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-port
        - name: MEMORY_CACHE_SIZE
          value: "1024"
        - name: PREFETCH_THRESHOLD
          value: "0.8"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cache-manager
  namespace: valeo-neuroerp
spec:
  selector:
    app: cache-manager
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP 