"""initial_migration

Revision ID: 9c70cf8e643c
Revises: 
Create Date: 2025-05-21 22:33:30.213658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c70cf8e643c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('touren',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournr', sa.Integer(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PLANUNG', 'AKTIV', 'ABGESCHLOSSEN', 'STORNIERT', name='tourstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_touren_id'), 'touren', ['id'], unique=False)
    op.create_index(op.f('ix_touren_tournr'), 'touren', ['tournr'], unique=True)
    op.create_table('picklisten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picklistnr', sa.Integer(), nullable=True),
    sa.Column('erstelltam', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('NEU', 'IN_BEARBEITUNG', 'ABGESCHLOSSEN', 'STORNIERT', name='picklistestatus'), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['touren.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picklisten_id'), 'picklisten', ['id'], unique=False)
    op.create_index(op.f('ix_picklisten_picklistnr'), 'picklisten', ['picklistnr'], unique=True)
    op.create_table('auftraege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belegnr', sa.Integer(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('art', sa.Enum('LIEFERUNG', 'RUECKNAHME', 'UMTAUSCH', name='auftragart'), nullable=False),
    sa.Column('status', sa.Enum('NEU', 'IN_BEARBEITUNG', 'ABGESCHLOSSEN', 'STORNIERT', name='auftragstatus'), nullable=False),
    sa.Column('pickliste_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pickliste_id'], ['picklisten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auftraege_belegnr'), 'auftraege', ['belegnr'], unique=True)
    op.create_index(op.f('ix_auftraege_id'), 'auftraege', ['id'], unique=False)
    op.create_table('auftragspositionen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artikelnr', sa.String(length=50), nullable=False),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('auftrag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftraege.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auftragspositionen_artikelnr'), 'auftragspositionen', ['artikelnr'], unique=False)
    op.create_index(op.f('ix_auftragspositionen_id'), 'auftragspositionen', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auftragspositionen_id'), table_name='auftragspositionen')
    op.drop_index(op.f('ix_auftragspositionen_artikelnr'), table_name='auftragspositionen')
    op.drop_table('auftragspositionen')
    op.drop_index(op.f('ix_auftraege_id'), table_name='auftraege')
    op.drop_index(op.f('ix_auftraege_belegnr'), table_name='auftraege')
    op.drop_table('auftraege')
    op.drop_index(op.f('ix_picklisten_picklistnr'), table_name='picklisten')
    op.drop_index(op.f('ix_picklisten_id'), table_name='picklisten')
    op.drop_table('picklisten')
    op.drop_index(op.f('ix_touren_tournr'), table_name='touren')
    op.drop_index(op.f('ix_touren_id'), table_name='touren')
    op.drop_table('touren')
    # ### end Alembic commands ###
