"""migration_20250522_084428

Revision ID: e77c8a185a46
Revises: 2d262ca4226b
Create Date: 2025-05-22 08:44:29.639493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77c8a185a46'
down_revision: Union[str, None] = '2d262ca4226b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KUNDE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name2', sa.String(), nullable=True),
    sa.Column('strasse', sa.String(), nullable=True),
    sa.Column('plz', sa.String(), nullable=True),
    sa.Column('ort', sa.String(), nullable=True),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('www', sa.String(), nullable=True),
    sa.Column('kundennr', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KUNDE_id'), 'KUNDE', ['id'], unique=False)
    op.create_index(op.f('ix_KUNDE_kundennr'), 'KUNDE', ['kundennr'], unique=False)
    op.create_table('WAAGE_MESSUNG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zeitstempel', sa.DateTime(), nullable=True),
    sa.Column('gewicht', sa.Float(), nullable=True),
    sa.Column('waage_id', sa.String(), nullable=True),
    sa.Column('belegnr', sa.String(), nullable=True),
    sa.Column('kundennr', sa.String(), nullable=True),
    sa.Column('artikelnr', sa.String(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bediener', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WAAGE_MESSUNG_id'), 'WAAGE_MESSUNG', ['id'], unique=False)
    op.create_table('WWS_ARTIKEL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.Integer(), nullable=True),
    sa.Column('artikelnr', sa.String(), nullable=True),
    sa.Column('bezeichn1', sa.String(), nullable=True),
    sa.Column('bezeichn2', sa.String(), nullable=True),
    sa.Column('einheit', sa.String(), nullable=True),
    sa.Column('warengruppe', sa.String(), nullable=True),
    sa.Column('vk1', sa.Float(), nullable=True),
    sa.Column('vk2', sa.Float(), nullable=True),
    sa.Column('vk3', sa.Float(), nullable=True),
    sa.Column('ek', sa.Float(), nullable=True),
    sa.Column('mwst', sa.Float(), nullable=True),
    sa.Column('bestand', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WWS_ARTIKEL_artikelnr'), 'WWS_ARTIKEL', ['artikelnr'], unique=False)
    op.create_index(op.f('ix_WWS_ARTIKEL_id'), 'WWS_ARTIKEL', ['id'], unique=False)
    op.create_table('ZAHLVORSCH',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faelldatum', sa.DateTime(), nullable=True),
    sa.Column('buchdatum', sa.DateTime(), nullable=True),
    sa.Column('konto', sa.String(), nullable=True),
    sa.Column('kundennr', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rechnbetrag', sa.Float(), nullable=True),
    sa.Column('skontierf', sa.Float(), nullable=True),
    sa.Column('netto', sa.Float(), nullable=True),
    sa.Column('restbetrag', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ZAHLVORSCH_id'), 'ZAHLVORSCH', ['id'], unique=False)
    op.create_table('ZUSATZFELDER_KUNDE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.Column('zid', sa.Integer(), nullable=True),
    sa.Column('zdatabase_id', sa.Integer(), nullable=True),
    sa.Column('verweis_id', sa.Integer(), nullable=True),
    sa.Column('verweis_dbid', sa.Integer(), nullable=True),
    sa.Column('inhalt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ZUSATZFELDER_KUNDE_id'), 'ZUSATZFELDER_KUNDE', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('min_stock_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('WWS_VERKAUF1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.Integer(), nullable=True),
    sa.Column('belegnr', sa.String(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('kundennr', sa.String(), nullable=True),
    sa.Column('belegart', sa.String(), nullable=True),
    sa.Column('betrag', sa.Float(), nullable=True),
    sa.Column('mwst_betrag', sa.Float(), nullable=True),
    sa.Column('gesamt_betrag', sa.Float(), nullable=True),
    sa.Column('bezahlt', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kundennr'], ['KUNDE.kundennr'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WWS_VERKAUF1_belegnr'), 'WWS_VERKAUF1', ['belegnr'], unique=False)
    op.create_index(op.f('ix_WWS_VERKAUF1_id'), 'WWS_VERKAUF1', ['id'], unique=False)
    op.create_table('WWS_WSTR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.Integer(), nullable=True),
    sa.Column('bediener', sa.String(), nullable=True),
    sa.Column('art', sa.String(), nullable=True),
    sa.Column('rechnungnr', sa.String(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('posnr', sa.Integer(), nullable=True),
    sa.Column('posart', sa.String(), nullable=True),
    sa.Column('artikelnr', sa.String(), nullable=True),
    sa.Column('bezeichn1', sa.String(), nullable=True),
    sa.Column('bezeichn2', sa.String(), nullable=True),
    sa.Column('kundennr', sa.String(), nullable=True),
    sa.Column('menge', sa.Float(), nullable=True),
    sa.Column('einheit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artikelnr'], ['WWS_ARTIKEL.artikelnr'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WWS_WSTR_id'), 'WWS_WSTR', ['id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('last_restock_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_table('TSE_TRANSAKTION',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belegnr', sa.String(), nullable=True),
    sa.Column('tse_id', sa.String(), nullable=True),
    sa.Column('tse_signatur', sa.String(), nullable=True),
    sa.Column('tse_zeitstempel', sa.DateTime(), nullable=True),
    sa.Column('tse_seriennummer', sa.String(), nullable=True),
    sa.Column('tse_signaturzaehler', sa.Integer(), nullable=True),
    sa.Column('verkauf_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['verkauf_id'], ['WWS_VERKAUF1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TSE_TRANSAKTION_belegnr'), 'TSE_TRANSAKTION', ['belegnr'], unique=False)
    op.create_index(op.f('ix_TSE_TRANSAKTION_id'), 'TSE_TRANSAKTION', ['id'], unique=False)
    op.create_table('WWS_VERKAUF2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.Integer(), nullable=True),
    sa.Column('kopf_id', sa.Integer(), nullable=True),
    sa.Column('artikelnr', sa.String(), nullable=True),
    sa.Column('bezeichn1', sa.String(), nullable=True),
    sa.Column('bezeichn2', sa.String(), nullable=True),
    sa.Column('menge', sa.Float(), nullable=True),
    sa.Column('einheit', sa.String(), nullable=True),
    sa.Column('einzelpreis', sa.Float(), nullable=True),
    sa.Column('gesamtpreis', sa.Float(), nullable=True),
    sa.Column('mwst_satz', sa.Float(), nullable=True),
    sa.Column('mwst_betrag', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artikelnr'], ['WWS_ARTIKEL.artikelnr'], ),
    sa.ForeignKeyConstraint(['kopf_id'], ['WWS_VERKAUF1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WWS_VERKAUF2_id'), 'WWS_VERKAUF2', ['id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_order_number'), 'order', ['order_number'], unique=True)
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitem_id'), 'orderitem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitem_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_order_order_number'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_WWS_VERKAUF2_id'), table_name='WWS_VERKAUF2')
    op.drop_table('WWS_VERKAUF2')
    op.drop_index(op.f('ix_TSE_TRANSAKTION_id'), table_name='TSE_TRANSAKTION')
    op.drop_index(op.f('ix_TSE_TRANSAKTION_belegnr'), table_name='TSE_TRANSAKTION')
    op.drop_table('TSE_TRANSAKTION')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_WWS_WSTR_id'), table_name='WWS_WSTR')
    op.drop_table('WWS_WSTR')
    op.drop_index(op.f('ix_WWS_VERKAUF1_id'), table_name='WWS_VERKAUF1')
    op.drop_index(op.f('ix_WWS_VERKAUF1_belegnr'), table_name='WWS_VERKAUF1')
    op.drop_table('WWS_VERKAUF1')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_ZUSATZFELDER_KUNDE_id'), table_name='ZUSATZFELDER_KUNDE')
    op.drop_table('ZUSATZFELDER_KUNDE')
    op.drop_index(op.f('ix_ZAHLVORSCH_id'), table_name='ZAHLVORSCH')
    op.drop_table('ZAHLVORSCH')
    op.drop_index(op.f('ix_WWS_ARTIKEL_id'), table_name='WWS_ARTIKEL')
    op.drop_index(op.f('ix_WWS_ARTIKEL_artikelnr'), table_name='WWS_ARTIKEL')
    op.drop_table('WWS_ARTIKEL')
    op.drop_index(op.f('ix_WAAGE_MESSUNG_id'), table_name='WAAGE_MESSUNG')
    op.drop_table('WAAGE_MESSUNG')
    op.drop_index(op.f('ix_KUNDE_kundennr'), table_name='KUNDE')
    op.drop_index(op.f('ix_KUNDE_id'), table_name='KUNDE')
    op.drop_table('KUNDE')
    # ### end Alembic commands ###
