apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: valeo-neuroerp
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/your-webhook-url'

    route:
      group_by: ['alertname', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'slack-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'slack-critical'
        group_wait: 10s
        repeat_interval: 1h

    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#apm-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

    - name: 'slack-critical'
      slack_configs:
      - channel: '#apm-critical'
        send_resolved: true
        title: '[KRITISCH] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        color: 'danger'

    templates:
    - '/etc/alertmanager/config/*.tmpl'

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname'] 