global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  # Multi-Agent System Metrics
  - job_name: 'valeo_mas'
    static_configs:
      - targets: ['mas:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  # Node Exporter Metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # MongoDB Metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: '/metrics'
    scheme: 'http'

  # Prometheus selbst
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Alert Manager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # Backup Service
  - job_name: 'backup'
    static_configs:
      - targets: ['backup:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'api_server'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8003']
        labels:
          service: 'erp_api'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  - job_name: 'celery'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['flower:5555']
        labels:
          service: 'celery' 